package com.kwabenaberko.openweathermaplib.constant

object Lang {
    val ARABIC: String? = "ar"
    val BULGARIAN: String? = "bg"
    val CATALAN: String? = "ca"
    val CZECH: String? = "cz"
    val GERMAN: String? = "de"
    val GREEK: String? = "el"
    val ENGLISH: String? = "en"
    val PERSIAN: String? = "fa"
    val FINNISH: String? = "fi"
    val FRENCH: String? = "fr"
    val GALICIAN: String? = "gl"
    val CROATIAN: String? = "hr"
    val HUNGARIAN: String? = "hu"
    val ITALIAN: String? = "it"
    val JAPANESE: String? = "ja"
    val KOREAN: String? = "kr"
    val LATVIAN: String? = "la"
    val LITHUANIAN: String? = "lt"
    val MACEDONIAN: String? = "mk"
    val DUTCH: String? = "nl"
    val POLISH: String? = "pl"
    val PORTUGUESE: String? = "pt"
    val ROMANIAN: String? = "ro"
    val RUSSIAN: String? = "ru"
    val SWEDISH: String? = "se"
    val SLOVAK: String? = "sk"
    val SLOVENIAN: String? = "sl"
    val SPANISH: String? = "es"
    val TURKISH: String? = "tr"
    val UKRAINIAN: String? = "ua"
    val VIETNAMESE: String? = "vi"
    val CHINESE_SIMPLIFIED: String? = "zh_cn"
    val CHINESE_TRADITIONAL: String? = "zh_tw"
}